{{- if and .Values.backend.enabled .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "c4genaisuite.fullname" . }}
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "c4genaisuite.commonSelectors" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
    - Egress
    - Ingress
  egress:
    - ports:
        - port: 443
          protocol: TCP
        - port: 5432
          protocol: TCP
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
    - to:
        - podSelector:
            matchLabels:
              {{- include "c4genaisuite.commonSelectors" . | nindent 14 }}
              app.kubernetes.io/component: reis
      ports:
        - port: 3201
          protocol: TCP
  ingress:
    - ports:
        - port: 3000
          protocol: TCP
{{- end }}
