{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c4genaisuite.fullname" . }}-backend
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  {{- if not .Values.backend.auth.existingAdminSecret }}
  AUTH_INITIAL_ADMIN_USERNAME: "{{ .Values.backend.auth.initialAdminUsername }}"
  {{- end }}
  {{- if not .Values.backend.auth.existingAdminSecret }}
  AUTH_INITIAL_ADMIN_PASSWORD: "{{ .Values.backend.auth.initialAdminPassword }}"
  {{- end }}
  {{- if not .Values.backend.auth.existingClientId }}
  AUTH_OAUTH_CLIENTID: "{{ .Values.backend.auth.clientId }}"
  {{- end }}
  {{- if not .Values.backend.auth.existingClientSecret }}
  AUTH_OAUTH_CLIENTSECRET: "{{ .Values.backend.auth.clientSecret }}"
  {{- end }}
  {{- if not .Values.backend.auth.existingMicrosoftClientId }}
  AUTH_MICROSOFT_CLIENTID: "{{ .Values.backend.auth.microsoftClientId }}"
  {{- end }}
  {{- if not .Values.backend.auth.existingMicrosoftClientSecret }}
  AUTH_MICROSOFT_CLIENTSECRET: "{{ .Values.backend.auth.microsoftClientSecret }}"
  {{- end }}
  {{- if not .Values.backend.auth.existingMicrosoftTenant }}
  AUTH_MICROSOFT_TENANT: "{{ .Values.backend.auth.microsoftTenant }}"
  {{- end }}
  {{- if not .Values.backend.postgresql.existingConnectionStringSecret }}
  DB_URL: "{{ .Values.backend.postgresql.connectionString }}"
  {{- end }}
  {{- if not .Values.backend.existingSessionSecret }}
  SESSION_SECRET: "{{ .Values.backend.sessionSecret }}"
  {{- end }}
{{- end }}
