{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "c4genaisuite.fullname" . }}-backend
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    {{- include "c4genaisuite.commonSelectors" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
