{{- if and .Values.backend.enabled .Values.backend.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "c4genaisuite.fullname" . }}-backend-metrics
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend-metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.backend.metrics.port }}
      targetPort: metrics
  selector:
    {{- include "c4genaisuite.commonSelectors" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
