{{- if .Values.reis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "c4genaisuite.fullname" . }}-reis
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: reis
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: web-deprecated
      port: 3201 # for backwards-compatibility
      targetPort: web
  selector:
    {{- include "c4genaisuite.commonSelectors" . | nindent 4 }}
    app.kubernetes.io/component: reis
{{- end }}
