{{- if and .Values.frontend.enabled .Values.frontend.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "c4genaisuite.fullname" . }}-frontend-metrics
  labels:
    {{- include "c4genaisuite.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 2019
      targetPort: admin-api
  selector:
    {{- include "c4genaisuite.commonSelectors" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
